### ISSUE TITLE
github action 相关信息

### ISSUE THREAD

**Issue by bxb100** [bxb100/blog#7]
* [生成 release log](https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes)

**Comment by bxb100** [comment]
* [输入参数多行](https://github.community/t/set-output-truncates-multiline-strings/16852)
* [echo multiline strings in github action](https://trstringer.com/github-actions-multiline-strings/)
* 同样的问题还出现在 setting error message 中(这里只讨论直接在 yaml 文件中输出的情况), 输出 `\n` 的文件只会输出第一行, 用如下方式解决: 
```shell
		  ERR_MSG=$(cat err.log)
          ERR_MSG="${ERR_MSG//'%'/'%25'}"
          ERR_MSG="${ERR_MSG//$'\n'/'%0A'}"
          ERR_MSG="${ERR_MSG//$'\r'/'%0D'}"
          echo "::error title=err::$ERR_MSG"
```

**Comment by bxb100** [comment]
* Anyway to check the error message and retry?
	1. 社区里面用 `||` 来 retry 命令, 但是我这个 shell 着实繁琐又不想写个 sh 文件, 忽略[^1]
	2. 还有种思路就是利用 `2> file` 输出错误信息, 判断[^3], 然后利用 workflow 的 API 来重新调用, 调用代码如下[^2]
		* 注意 `failure()` 标识[此 job 中上一个 step 失败](https://docs.github.com/en/actions/learn-github-actions/expressions#failure)
		* `${{ secrets.GH_PAT }}` 注意给 workflow 的权限
		* **可能导致无限调用**
```yaml
      - name: Failed
        if: ${{ failure() }}
        run: |
          if grep -q 'errorMessage' err.log;
          then curl --location --request POST 'https://api.github.com/repos/xxx/xxx/actions/workflows/xxxx/dispatches' \
          --header 'Accept: application/vnd.github.v3+json' \
          --header 'Authorization: token ${{ secrets.GH_PAT }}' \
          --header 'Content-Type: application/json' \
          --data-raw '{
              "ref": "main",
              "inputs": {
                  "xxx": "${{github.event.inputs.xxx}}"
              }
          }'
          fi
```







[^1]: https://github.community/t/how-to-retry-a-failed-step-in-github-actions-workflow/125880
[^2]: https://docs.github.com/en/rest/reference/actions#create-a-workflow-dispatch-event Create a workflow dispatch event
[^3]: https://stackoverflow.com/questions/11287861/how-to-check-if-a-file-contains-a-specific-string-using-bash

**Comment by bxb100** [comment]
## 如何上传可执行文件到 release 中 (draft)

1. 首先需要先创建一个 git ref tag 对应的 draft release, 注意此时的 tag 如果没有的话 GitHub 也不会主动给你绑定
<img width="1115" alt="image" src="https://user-images.githubusercontent.com/20685961/195251932-4b084fde-8bf3-4913-b1ea-b315661f8f8d.png">

see https://gist.github.com/bxb100/d2fedcb3cdc897062ee03920d6ae83be

2. upload the artifact
3. download artifacts, and compress them
4. using `gh` upload to the release
```yaml
     - name: Upload
        run: |
          until gh release upload --clobber --repo ${{ github.repository }} ${{ github.event.inputs.tag }} *.zip *.tar.gz; do
            echo "Attempt $((++attempts)) to upload release artifacts failed. Will retry in 20s"
            sleep 20
          done
        timeout-minutes: 10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

## Examples
-  https://github.com/temporalio/sdk-java/actions/runs/3132010440/workflow
